---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[sphinx]

- name: centos-6.5
  run_list:
    - recipe[sphinx]

suites:
- name: source-install-http
  run_list:
  - recipe[sphinx_test]
  attributes:
    sphinx:
      use_mysql: true
      use_postgres: true

- name: source-install-svn
  run_list:
  - recipe[sphinx_test]
  attributes:
    sphinx:
      use_mysql: true
      source:
        retrieve_method: 'svn'

- name: package-install
  run_list:
  - recipe[sphinx_test]
  attributes:
    sphinx:
      install_method: 'package'

- name: rpm-install
  run_list:
  - recipe[sphinx_test]
  attributes:
    sphinx:
      install_method: 'rpm'
  excludes:
    - ubuntu-14.04
